### ISSUE TITLE
ტექსტების line-height-ები ოდნავ გავზარდოთო

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/Fonts.geolab.edu.ge-Back-End-#3]
- ისტორიის ნაწილზე
- სულ ზემოთ რომ დიდი ტექსტია საბეჭდი მანქანის გვერდით, მანდ

**Comment by kote-d** [comment]
საბეჭდი მანქანის ტექსტზე იყო 1.1em, ეხლა არის 1.3em. ისტორიაზე იყო 1.5em და გახდა 1.7em. თუ კიდე შესაცვლელია რეოფენ და გავაკეთებ. ოღონდ მოაყოლე მოვუმატო თუ მოვაკლო ;)
