### ISSUE TITLE
ფონტებში "შრიფტის მაგალითი" ცოტა ქვემოთ ჩამოვწიოთო

### ISSUE THREAD

**Issue by AnanoAspanidze** [GeoLabJuniors/Fonts.geolab.edu.ge-Back-End-#6]
ეს ნაწილი
![image](https://user-images.githubusercontent.com/17623524/29581497-8c7c3a8a-878a-11e7-9264-a52ab47631b5.png)

**Comment by kote-d** [comment]
20px იყო და ეხლა 30px არის. თუ საჭიროა კიდე 5px აიტანს :P
